name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: pnpm setup
        uses: pnpm/action-setup@91ab88e2619ed1f46221f0ba42d1492c02baf788 # v6.0.6
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm run test

      - name: Check
        run: pnpm exec biome check . --error-on-warnings

      - name: Build
        run: pnpm run build
